- name: Angular Full CI
  # You may pin to the exact commit or the version.
  # uses: colbyhill21/angular-full-ci@a3489087f6a715db335078f999c01d422a254a6c
  uses: colbyhill21/angular-full-ci@v1.0
  with:
    # Command to run tests on your project, do not prepend with "npm", it is already included.
    testcommand: 
    # Set to true in order to run mocha tests. This option will install mocha on the image.
    mocha: # optional
